### ISSUE TITLE
CREDEBL Documentation - 1.2.2: API Reference

### ISSUE THREAD

**Issue by prasadgkalamkar** [credebl/docs#22]
Update docs to include credebl platform APIs

- [x] Research about Plugin for astro docs build [starlight-openapi](https://starlight-openapi.vercel.app/getting-started/)
- [x] Local setup
- [x] Initial implementation
  - ~~[ ] Facing an issue regarding types in~~ This is resolved by updating all the package versions
    - https://github.com/withastro/starlight/issues/1161 
    - https://github.com/withastro/starlight/issues/860
- [ ] Credo controller API reference implementation
  - [x] Initial implementation
  - [ ] Need to change the API references Id's as they were duplicate for dedicated and multi-tenant endpoints
- [ ] Platform API reference implementation
- [ ] Update the paging/ordering of this section according to CREDEBL docs specification

**Comment by GHkrishna** [comment]
Closing as fixed
